version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "order-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ps2e4msk3qvy"
s3_prefix = "order-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
